name: Build

on:
  push:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libsdl2-dev libsdl2-ttf-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
          make
          strip --strip-unneeded laserkombat
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: laserkombat-linux
          path: |
            laserkombat
            assets
            COPYING
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
          update: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" .
          cmake --build .
          strip --strip-unneeded laserkombat.exe
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: laserkombat-windows
          path: |
            laserkombat.exe
            assets
            COPYING

  Vita:
    runs-on: ubuntu-latest
    container: vitasdk/buildscripts:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apk add bash pkgconf curl cmake make
          vdpm sdl2
          vdpm sdl2_ttf
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${VITASDK}/share/vita.toolchain.cmake" .
          make
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: laserkombat-vita
          path: |
            laserkombat.vpk
            COPYING

  Release:
    needs: [Linux, Windows, Vita]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [linux, windows, vita]
    steps:
    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/download-artifact@v2
    - name: Zip artifacts
      run: |
        zip -r laserkombat-${{matrix.build}}.zip laserkombat-${{matrix.build}}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: laserkombat-${{matrix.build}}.zip
        tag_name: ${{ steps.tag.outputs.VERSION }}
        name: Laser Kombat Revised version ${{ steps.tag.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
